// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Data;
using MakingCents.Database.Models;

#pragma warning disable 1573, 1591
#nullable enable

namespace MakingCents.Database
{
	public partial class DbContext : DataConnection
	{
		partial void InitDataContext();

		public ITable<VersionHistory> VersionHistories => this.GetTable<VersionHistory>();
	}
}
